services:
  - type: web # <--- التغيير الأهم: من worker إلى web
    name: pro-trading-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && pip install flask" # <-- أضفنا Flask
    startCommand: "python bot.py" # <-- سنعدل ملف البوت ليبدأ خادم ويب صغير
    healthCheckPath: /health # <-- مسار لفحص صحة الخدمة
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TWELVE_DATA_API_KEY_1
        sync: false
      - key: TWELVE_DATA_API_KEY_2
        sync: false
